<?php
	$Action						= $_POST["Action"];
	$ColorIDs					= $_POST["ColorIDs"];
	$GotoPage					= $_POST["GotoPage"];
	$ProductID					= $_POST["ProductID"];
	$Display_ActiveItems_By		= $_POST["Display_ActiveItems_By"];
	$Display_ActiveItems_In		= $_POST["Display_ActiveItems_In"];
	$prroductid_copy			= $_POST["prroductid_copy"];
	$Edit_IsActive				= $_POST["Edit_IsActive"];
	$Edit_Cat1ID				= $_POST["Edit_Cat1ID"];
	$Edit_Cat2ID				= $_POST["Edit_Cat2ID"];
	$Edit_BrandName1			= $_POST["Edit_BrandName1"];
	$Edit_BrandName2			= $_POST["Edit_BrandName2"];
	$Edit_ProductName			= $_POST["Edit_ProductName"];
	$Edit_ProductDescription	= $_POST["Edit_ProductDescription"];
	$Edit_NoticeToPurchasers	= $_POST["Edit_NoticeToPurchasers"];
	$Edit_SearchEngineTags		= $_POST["Edit_SearchEngineTags"];
	$Edit_Player1				= $_POST["Edit_Player1"];
	$Edit_Country2				= $_POST["Edit_Country2"];
	$Edit_MadeOfMaterial		= $_POST["Edit_MadeOfMaterial"];
	$Edit_UnitPrice				= $_POST["Edit_UnitPrice"];
	$Edit_UnitPriceOnSale		= $_POST["Edit_UnitPriceOnSale"];
	$Edit_PrepackQuantity		= $_POST["Edit_PrepackQuantity"];
	$Edit_Weight_Pounds			= $_POST["Edit_Weight_Pounds"];
	$Free_Shipping				= $_POST["Free_Shipping"];
	$Edit_IsThisBackOrderItem	= $_POST["Edit_IsThisBackOrderItem"];
	$Edit_ForMenOrWomen			= $_POST["Edit_ForMenOrWomen"];
	$Edit_SizeChartID			= $_POST["Edit_SizeChartID"];
	$personalize				= $_POST["personalize"];
	$Edit_QuantityDiscountID	= $_POST["Edit_QuantityDiscountID"];
	$Edit_MatchesWithProduct1	= $_POST["Edit_MatchesWithProduct1"];
	$Edit_MatchesWithProduct2	= $_POST["Edit_MatchesWithProduct2"];
	$Edit_MatchesWithProduct3	= $_POST["Edit_MatchesWithProduct3"];
	$Edit_MatchesWithProduct4	= $_POST["Edit_MatchesWithProduct4"];
	$Edit_MatchesWithProduct5	= $_POST["Edit_MatchesWithProduct5"];
	$Edit_MatchesWithProduct6	= $_POST["Edit_MatchesWithProduct6"];
	
	//DEBUG
	echo $Action;
	echo "<br/>";
	echo $ColorIDs;
	echo "<br/>";
	echo $GotoPage;
	echo "<br/>";
	echo $ProductID;
	echo "<br/>";
	echo $Display_ActiveItems_By;
	echo "<br/>";
	echo $Display_ActiveItems_In;
	echo "<br/>";
	echo $prroductid_copy;
	echo "<br/>";
	echo $Edit_IsActive;
	echo "<br/>";
	echo $Edit_Cat1ID;
	echo "<br/>";
	echo $Edit_Cat2ID;
	echo "<br/>";
	echo $Edit_BrandName1;
	echo "<br/>";
	echo $Edit_BrandName2;
	echo "<br/>";
	echo $Edit_ProductName;
	echo "<br/>";
	echo $Edit_ProductDescription;
	echo "<br/>";
	echo $Edit_NoticeToPurchasers;
	echo "<br/>";
	echo $Edit_SearchEngineTags;
	echo "<br/>";
	echo $Edit_Player1;
	echo "<br/>";
	echo $Edit_Country2;
	echo "<br/>";
	echo $Edit_MadeOfMaterial;
	echo "<br/>";
	echo $Edit_UnitPrice;
	echo "<br/>";
	echo $Edit_UnitPriceOnSale;
	echo "<br/>";
	echo $Edit_PrepackQuantity;
	echo "<br/>";
	echo $Edit_Weight_Pounds;
	echo "<br/>";
	echo $Free_Shipping;
	echo "<br/>";
	echo $Edit_IsThisBackOrderItem;
	echo "<br/>";
	echo $Edit_ForMenOrWomen;
	echo "<br/>";
	echo $Edit_SizeChartID;
	echo "<br/>";
	echo $personalize;
	echo "<br/>";
	echo $Edit_QuantityDiscountID;
	echo "<br/>";
	echo $Edit_MatchesWithProduct1;
	echo "<br/>";
	echo $Edit_MatchesWithProduct2;
	echo "<br/>";
	echo $Edit_MatchesWithProduct3;
	echo "<br/>";
	echo $Edit_MatchesWithProduct4;
	echo "<br/>";
	echo $Edit_MatchesWithProduct5;
	echo "<br/>";
	echo $Edit_MatchesWithProduct6;
	//END DEBUG
?>